### ISSUE TITLE
SDP-MD09

### ISSUE THREAD

**Issue by judielaine** [KantaraInitiative/SAMLprofiles#81] opened 2018-05-24 16:45 UTC
This is definitely an issue for interop in the general. It may be hidden in hub-spoke feds.

**Comment by scantor** [comment] 2018-05-31 14:53
Removed confusing issue number conflict, this is issue 7 from the wiki table.

**Comment by scantor** [comment] 2018-05-31 14:59
Moved over to Eric since he proposed a fix.

**Comment by ergood** [comment] 2018-06-06 22:42
Adding references: 
This issue is a duplicate of #80, and is addressed by #87.

**Closed** 2018-07-26 22:29 UTC
