### ISSUE TITLE
(Response to Feedback Item 18) Identifier scoping; no change to normative but addition to nonormative text 

### ISSUE THREAD

**Issue by judielaine** [KantaraInitiative/SAMLprofiles#94] opened 2018-05-31 16:34 UTC

**Comment by ergood** [comment] 2018-06-14 19:01
Is this effectively a duplicate of #95?

**Comment by nckroy** [comment] 2018-07-12 19:13
Yes, I will delete this dupe issue.

**Comment by nckroy** [comment] 2018-07-12 19:13
Closed, duplicates #95.

**Closed by nckroy** 2018-07-12 19:13 UTC
Labels: question
